source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.8.2"
gem "jekyll-sass-converter", "~> 2.0"

group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-seo-tag"
  gem "jekyll-include-cache"
end

gem "webrick"
